import { describe, expect, it } from 'vitest';
import { mergeAiExtraction } from '@/features/discovery/enrichment';
import type { ImportedEventDraft, ExtractedRaceEvent } from '@/features/importer/url-import';

const draft: ImportedEventDraft = { name:'Prova',slug:'prova',shortDescription:'',description:'',startDate:null,startTime:'',city:'',state:'MG',venue:'',address:'',organizerName:'',category:'rua',priceFrom:null,registrationUrl:'',regulationUrl:'',officialUrl:'https://example.com',coverImageUrl:'',distances:[],sourceUrl:'https://example.com',fieldsFound:[] };
const ai: ExtractedRaceEvent = { name:'Prova',date:'2026-10-18T00:00:00.000Z',startTime:null,city:'Itajubá',state:'MG',venue:null,address:null,distances:['5 km'],price:null,organizerName:null,registrationUrl:null,coverImageUrl:null };
describe('merge conservador da extração IA', () => {
  it('preenche somente ausentes e marca provenance ai', () => { const result=mergeAiExtraction(draft,{event:{name:'Prova',date:null,startTime:null,city:null,state:'MG',venue:null,address:null,distances:[],price:null,organizerName:null,registrationUrl:null,coverImageUrl:null},fieldSources:{state:'json_ld'},extractionQuality:{status:'insufficient',missingEssentialFields:['startDate','city'],missingImportantFields:[],conflicts:[]},shouldUseAiFallback:true},ai); expect(result.draft.startDate).toContain('2026-10-18'); expect(result.draft.city).toBe('Itajubá'); expect(result.extraction.fieldSources.city).toBe('ai'); expect(result.draft.distances).toHaveLength(1); });
  it('preserva data determinística e mantém conflito', () => { const result=mergeAiExtraction({...draft,startDate:'2026-10-10T00:00:00.000Z'},{event:{name:'Prova',date:'2026-10-10T00:00:00.000Z',startTime:null,city:null,state:'MG',venue:null,address:null,distances:[],price:null,organizerName:null,registrationUrl:null,coverImageUrl:null},fieldSources:{startDate:'json_ld'},extractionQuality:{status:'partial',missingEssentialFields:[],missingImportantFields:[],conflicts:[]},shouldUseAiFallback:false},{...ai,date:'2026-10-25T00:00:00.000Z'},[{field:'startDate',values:[{value:'2026-10-10',source:'json_ld'},{value:'2026-10-25',source:'ai'}]}]); expect(result.draft.startDate).toContain('2026-10-10'); expect(result.extraction.extractionQuality.conflicts).toHaveLength(1); });
});
