import { describe, expect, it } from 'vitest';
import { aggregateResearchTokens, buildDeterministicResearchQueries, compactEvidenceContext, createKnownUrlDiscoveryProvider, deterministicResolvedFields, isEvidenceFirstResearchEnabled, rankEvidenceUrls, resolveRaceEvidence, selectEvidenceDocuments, type RaceEvidenceDocument } from '@/features/discovery/evidence-first';
import type { ResearchInput } from '@/features/discovery/research';
const input: ResearchInput = { sourceUrl: 'https://official.example/race', event: { name: 'Corrida Teste', date: '2026-10-24', startTime: null, city: 'Itajubá', state: 'MG', venue: null, address: null, distances: ['5 km'], price: null, organizerName: null, registrationUrl: 'https://inscricao.example/race', coverImageUrl: null } };
const doc = (domain: string, text: string): RaceEvidenceDocument => ({ url: `https://${domain}/race`, domain, text, title: 'Race', sourceType: 'registration_platform', trustLevel: 'A', sourceMatchScore: 90, sourceWeight: 27, editionMatch: 'same_edition', extractedAt: new Date().toISOString(), provenance: { discoveryMethod: 'known_url' } });
describe('evidence-first research architecture', () => {
  it('builds at most two deterministic queries and prefers known URLs', async () => { expect(buildDeterministicResearchQueries(input)).toHaveLength(2); const urls = await createKnownUrlDiscoveryProvider().discover(input); expect(urls[0].url).toBe(input.sourceUrl); expect(urls).toHaveLength(2); });
  it('ranks and deduplicates documents by domain, with max three documents and six thousand chars', () => { const docs = [doc('a.example', 'a'), doc('a.example', 'better'), doc('b.example', 'b'), doc('c.example', 'c'), doc('d.example', 'd')]; expect(selectEvidenceDocuments(docs)).toHaveLength(3); expect(compactEvidenceContext(docs).length).toBeLessThanOrEqual(6000); expect(rankEvidenceUrls(input, [{ url: input.sourceUrl, domain: 'official.example', discoveryMethod: 'known_url' }, { url: 'https://other.example', domain: 'other.example', discoveryMethod: 'deterministic_query' }])[0].url).toBe(input.sourceUrl); });
  it('keeps deterministic fields and uses a structured call without web tools', async () => { expect(deterministicResolvedFields(input.event)).toContain('name'); const calls: unknown[] = []; const result = await resolveRaceEvidence({ create: async (request) => { calls.push(request); return { output_text: '{"facts":{}}', usage: { input_tokens: 10, output_tokens: 4 } }; } }, { model: 'gpt-5.5', input: 'unresolved fields only', schema: { type: 'object' } }); expect(result.totalTokens).toBe(14); expect((calls[0] as Record<string, unknown>).text).toBeTruthy(); expect((calls[0] as Record<string, unknown>).tools).toBeUndefined(); });
  it('aggregates tokens from the official persisted components', () => { expect(aggregateResearchTokens([{ inputTokens: 10, outputTokens: 4, totalTokens: 99 }, { inputTokens: 2, outputTokens: 3 }])).toEqual({ inputTokens: 12, outputTokens: 7, totalTokens: 19 }); });
  it('keeps the feature flag disabled by default', () => { expect(isEvidenceFirstResearchEnabled({})).toBe(false); });
});
