'use client';
import { useState } from 'react';
import { ArrowLeft, Download, ShieldCheck, Trash2 } from 'lucide-react';
import Link from 'next/link';
import { AdminEventForm } from '@/features/admin/event-form';
import type { ImportedEventDraft } from './url-import';
import { mergeEventImports, type ImportConflict } from './merge-imports';
import type { RaceEvent } from '@/features/events/types';
import { isPastStart } from '@/features/events/discovery';

function toEvent(draft: ImportedEventDraft, sources: ImportedEventDraft[]): RaceEvent {
  return { id:'',slug:draft.slug,name:draft.name,short_description:draft.shortDescription,description:draft.description,start_date:draft.startDate || '',end_date:null,city:draft.city,state:draft.state,country:'BR',venue:draft.venue,address:draft.address,latitude:null,longitude:null,organizer_name:draft.organizerName,event_category:draft.category,official_url:draft.officialUrl,registration_url:draft.registrationUrl,regulation_url:draft.regulationUrl,price_from:draft.priceFrom,cover_image_url:draft.coverImageUrl || '/images/runners.jpg',cover_image_source:draft.coverImageUrl ? 'official':'fallback',has_usable_official_image:Boolean(draft.coverImageUrl),short_tagline:draft.shortDescription.slice(0,100),status:'draft',organizer_verified:false,event_distances:draft.distances,event_sources:sources.map(source => ({source_name:'Importação por URL',source_url:source.sourceUrl,source_method:'url',last_verified_at:new Date().toISOString()}))};
}
async function importUrl(url: string): Promise<ImportedEventDraft> { const response = await fetch('/api/admin/import-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})}); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível importar a página.'); return data.draft; }

export function ImportPage(){
  const [url,setUrl]=useState(''),[draft,setDraft]=useState<ImportedEventDraft|null>(null),[sources,setSources]=useState<ImportedEventDraft[]>([]),[conflicts,setConflicts]=useState<ImportConflict[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false),[secondaryUrl,setSecondaryUrl]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const imported=await importUrl(url);setDraft(imported);setSources([imported]);}catch(e){setError(e instanceof Error?e.message:'Não foi possível importar a página.')}finally{setBusy(false)}}
  async function addSource(){if(!secondaryUrl.trim()||sources.length>=3)return;setAdding(true);setError('');try{const secondary=await importUrl(secondaryUrl);const merged=mergeEventImports(draft!,secondary);setDraft(merged.draft);setSources([...sources,secondary]);setConflicts([...conflicts,...merged.conflicts]);setSecondaryUrl('');}catch(e){setError(e instanceof Error?e.message:'Não foi possível importar a fonte complementar.')}finally{setAdding(false)}}
  function removeSource(index:number){if(sources.length<=1)return;const next=sources.filter((_,i)=>i!==index);let merged=next[0];const nextConflicts:ImportConflict[]=[];for(const source of next.slice(1)){const result=mergeEventImports(merged,source);merged=result.draft;nextConflicts.push(...result.conflicts);}setSources(next);setDraft(merged);setConflicts(nextConflicts);}
  function resetImport(){setDraft(null);setSources([]);setConflicts([]);setError('');setUrl('');setSecondaryUrl('');}
  const critical=conflicts.some(c=>['startDate','city','state'].includes(c.field));
  const missing = draft ? ['startDate','city','state','distances','registrationUrl'].filter(field => { const value = draft[field as keyof ImportedEventDraft]; return !value || (Array.isArray(value) && value.length === 0); }) : [];
  const hostname = (value: string) => { try { return new URL(value).hostname; } catch { return value; } };
  return <><div className="admin-heading"><div><Link href="/admin/eventos" className="text-button"><ArrowLeft size={16}/>Eventos</Link><h1>Importar corrida por URL</h1></div></div>{!draft&&<form className="import-url-form" onSubmit={submit}><label>URL da página da corrida<input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://exemplo.com/corrida"/></label><button className="button" disabled={busy}><Download size={18}/>{busy?'Importando…':'Importar dados'}</button><p className="admin-note"><ShieldCheck size={16}/>A página será acessada apenas no backend, sem executar JavaScript.</p>{error&&<p className="error-message" role="alert">{error}</p>}</form>}{draft&&<><div className="import-notice"><strong>{draft.startDate && isPastStart(draft.startDate) ? 'Esta corrida já ocorreu.' : 'Dados importados automaticamente. Revise antes de salvar.'}</strong><span>{draft.fieldsFound.length} campos encontrados · origem: {draft.sourceUrl}</span></div><section className="admin-note"><strong>Fontes</strong>{sources.map((source,index)=><div key={source.sourceUrl} style={{display:'flex',justifyContent:'space-between',gap:12}}><span>{index+1}. {hostname(source.sourceUrl)}</span>{sources.length>1&&<button type="button" className="text-button" onClick={()=>removeSource(index)}><Trash2 size={14}/>Remover</button>}</div>)}{sources.length<3&&<><button type="button" className="text-button" onClick={()=>setAdding(!adding)}>Adicionar outra fonte</button>{adding&&<div><label>URL complementar<input type="url" value={secondaryUrl} onChange={e=>setSecondaryUrl(e.target.value)} placeholder="https://outra-fonte.com/corrida"/></label><button type="button" className="button" onClick={addSource} disabled={adding||!secondaryUrl}>{adding?'Importando…':'Importar fonte'}</button></div>}</>}</section><section className="admin-note"><strong>Dados encontrados</strong><span>{draft.fieldsFound.length ? draft.fieldsFound.join(', ') : 'Nenhum campo identificado'}</span>{missing.length > 0 && <span> Ainda faltando: {missing.join(', ')}.</span>}</section>{conflicts.length>0&&<div className="error-message">Encontramos informações diferentes entre as fontes.<ul>{conflicts.map((c,i)=><li key={`${c.field}-${i}`}>{c.field}</li>)}</ul>{critical&&<strong>Resolva as informações divergentes antes de salvar.</strong>}</div>}<AdminEventForm event={toEvent(draft,sources)} forceDraft={draft.startDate && isPastStart(draft.startDate) ? 'finished' : true} sourceMethod="url" disableSave={critical}/><button type="button" className="text-button" onClick={resetImport}>← Importar outra URL</button></>}</>;
}