'use client';
import { useState } from 'react';
import { ArrowLeft, Download, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { AdminEventForm } from '@/features/admin/event-form';
import type { ImportedEventDraft } from './url-import';
import type { RaceEvent } from '@/features/events/types';
function toEvent(draft: ImportedEventDraft): RaceEvent { const start=draft.startDate || new Date().toISOString(); return { id:'',slug:'',name:draft.name,short_description:draft.shortDescription,description:draft.description,start_date:start,end_date:null,city:draft.city,state:draft.state,country:'BR',venue:draft.venue,address:draft.address,latitude:null,longitude:null,organizer_name:draft.organizerName,event_category:draft.category,official_url:draft.officialUrl,registration_url:draft.registrationUrl,regulation_url:draft.regulationUrl,price_from:draft.priceFrom,cover_image_url:draft.coverImageUrl || '/images/runners.jpg',cover_image_source:draft.coverImageUrl ? 'official':'fallback',has_usable_official_image:Boolean(draft.coverImageUrl),short_tagline:draft.shortDescription.slice(0,100),status:'draft',organizer_verified:false,event_distances:draft.distances,event_sources:[{source_name:'Importação por URL',source_url:draft.sourceUrl,last_verified_at:new Date().toISOString()}]}; }
export function ImportPage(){ const [url,setUrl]=useState(''),[draft,setDraft]=useState<ImportedEventDraft|null>(null),[duplicates,setDuplicates]=useState<{name:string;city:string;state:string;start_date:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false); async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setDraft(null);try{const r=await fetch('/api/admin/import-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await r.json();if(!r.ok)throw new Error(data.error);setDraft(data.draft);setDuplicates(data.duplicates||[]);}catch(e){setError(e instanceof Error?e.message:'Não foi possível importar a página.')}finally{setBusy(false)}} function resetImport(){setDraft(null);setDuplicates([]);setError('');setUrl('');} return <><div className="admin-heading"><div><Link href="/admin/eventos" className="text-button"><ArrowLeft size={16}/>Eventos</Link><h1>Importar corrida por URL</h1></div></div>{!draft&&<form className="import-url-form" onSubmit={submit}><label>URL da página da corrida<input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://exemplo.com/corrida"/></label><button className="button" disabled={busy}><Download size={18}/>{busy?'Importando…':'Importar dados'}</button><p className="admin-note"><ShieldCheck size={16}/>A página será acessada apenas no backend, sem executar JavaScript. URLs internas e redes privadas são bloqueadas.</p>{error&&<p className="error-message" role="alert">{error} Você ainda pode cadastrar a corrida manualmente.</p>}</form>}{draft&&<><div className="import-notice"><strong>Dados importados automaticamente. Revise antes de salvar.</strong><span>{draft.fieldsFound.length} campos encontrados · origem: {draft.sourceUrl}</span></div>{duplicates.length>0&&<p className="error-message">Possível evento já cadastrado: {duplicates.map(d=>`${d.name} — ${d.city} · ${d.state}`).join('; ')}. Você ainda pode revisar e salvar.</p>}<AdminEventForm event={toEvent(draft)} forceDraft sourceMethod="url"/><button type="button" className="text-button" onClick={resetImport}>← Importar outra URL</button></>}</>; }
