import dns from 'node:dns/promises';
import net from 'node:net';
import { z } from 'zod';

export interface ImportedEventDraft {
  name: string; shortDescription: string; description: string; startDate: string; startTime: string;
  city: string; state: string; venue: string; address: string; organizerName: string; category: 'rua'|'trail'|'night'|'kids';
  priceFrom: number | null; registrationUrl: string; regulationUrl: string; officialUrl: string; coverImageUrl: string;
  distances: { label: string; distance_km: number | null; category: string }[]; sourceUrl: string; fieldsFound: string[];
}
export const importUrlSchema = z.string().trim().url().max(2000).refine(v => /^https?:\/\//i.test(v), 'Use uma URL http:// ou https://.');
function ipBlocked(ip: string) { const version = net.isIP(ip); if (version === 4) { const [a,b] = ip.split('.').map(Number); return a === 10 || a === 127 || a === 0 || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) || a >= 224; } if (version === 6) { const normalized = ip.toLowerCase(); return normalized === '::1' || normalized.startsWith('fc') || normalized.startsWith('fd') || normalized.startsWith('fe8') || normalized.startsWith('fe9') || normalized.startsWith('fea') || normalized.startsWith('feb'); } return true; }
export async function assertSafeImportUrl(raw: string) { const parsed = importUrlSchema.parse(raw); const url = new URL(parsed); if (url.username || url.password || url.port && !['80','443'].includes(url.port)) throw new Error('URL não permitida.'); const host = url.hostname.toLowerCase(); if (host === 'localhost' || host.endsWith('.localhost') || host.endsWith('.local') || host === 'metadata.google.internal' || host === '169.254.169.254') throw new Error('URL interna bloqueada.'); const addresses = await dns.lookup(host, { all: true, verbatim: true }); if (!addresses.length || addresses.some(a => ipBlocked(a.address))) throw new Error('O endereço aponta para uma rede privada e foi bloqueado.'); return url.toString(); }
const clean = (v: string | undefined) => (v || '').replace(/\s+/g, ' ').trim();
const decode = (v: string) => clean(v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>'));
function tag(html: string, name: string, attr: string, value: string) { const re = new RegExp(`<${name}[^>]*${attr}=["']${value}["'][^>]*>`, 'i'); const m = html.match(re); return m ? decode(m[1] || m[0].replace(/.*content=["']([^"']*)["'].*/i,'$1')) : ''; }
function titleTag(html: string) { const m=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i); return m ? decode(m[1]) : ''; }
type JsonLdRecord = Record<string, unknown>;
function isRecord(value: unknown): value is JsonLdRecord {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
function jsonLd(html: string): JsonLdRecord[] { return [...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].flatMap(m => { try { const parsed: unknown = JSON.parse(m[1]); return Array.isArray(parsed) ? parsed : [parsed]; } catch { return []; } }).flatMap(value => { if (!isRecord(value)) return []; const graph = value['@graph']; return Array.isArray(graph) ? graph : [value]; }).filter(isRecord); }
const textOf = (html: string) => decode(html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' '));
function dateValue(v: unknown) { const s = typeof v === 'string' ? v : ''; if (!s) return ''; const iso = Date.parse(s); if (!Number.isNaN(iso)) return new Date(iso).toISOString(); const m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/); return m ? new Date(`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}T00:00:00-03:00`).toISOString() : ''; }
function distances(text: string) { const found = new Map<number|string,{label:string;distance_km:number|null;category:string}>(); const patterns=[/(\d{1,3}(?:[,.]\d{1,3})?)\s*(?:km|k)\b/gi,/\b(meia\s*maratona|maratona|caminhada|kids)\b/gi]; for(const p of patterns) for(const m of text.matchAll(p)){const raw=m[1]; const n=/^\d/.test(raw) ? Number(raw.replace(',','.')) : raw.toLowerCase().includes('meia') ? 21.097 : raw.toLowerCase().includes('maratona') ? 42.195 : null; const label=n ? `${n % 1 ? n.toString().replace('.',',') : n} km` : raw; found.set(n ?? label,{label,distance_km:n,category:raw.toLowerCase().includes('trail')?'trail':'rua'});} return [...found.values()].slice(0,20); }
export function extractEventMetadata(html: string, sourceUrl: string): ImportedEventDraft { const graph=jsonLd(html).find(x => {const t=x['@type']; return t === 'Event' || (Array.isArray(t) && t.includes('Event')); }) || {}; const loc=isRecord(graph.location) ? graph.location : {}; const addr=isRecord(loc.address) ? loc.address : {}; const offers=isRecord(graph.offers) ? graph.offers : {}; const organizer=isRecord(graph.organizer) ? graph.organizer : {}; const name=clean(String(graph.name || tag(html,'meta','property','og:title') || tag(html,'meta','name','twitter:title') || titleTag(html))); const description=clean(String(graph.description || tag(html,'meta','property','og:description') || tag(html,'meta','name','description'))); const start=dateValue(graph.startDate); const image=clean(String(graph.image || tag(html,'meta','property','og:image'))); const allText=textOf(html); const ds=distances(`${name} ${description} ${allText}`); const draft: ImportedEventDraft={name,shortDescription:description.slice(0,240),description,startDate:start,startTime:start ? start.slice(11,16) : '',city:clean(String(addr.addressLocality || '')),state:clean(String(addr.addressRegion || '')).toUpperCase(),venue:clean(String(loc.name || '')),address:clean(String(addr.streetAddress || '')),organizerName:clean(String(organizer.name || '')),category:/trail|montanha/i.test(allText)?'trail':/night|noturna/i.test(allText)?'night':/kids|infantil/i.test(allText)?'kids':'rua',priceFrom:offers.price ? Number(offers.price) : null,registrationUrl:clean(String(offers.url || '')),regulationUrl:'',officialUrl:sourceUrl,coverImageUrl:image,distances:ds,sourceUrl,fieldsFound:[]}; for(const [key,value] of Object.entries(draft)) if(value && (!Array.isArray(value) || value.length)) draft.fieldsFound.push(key); return draft; }
export async function fetchEventPage(rawUrl: string): Promise<ImportedEventDraft> { const url=await assertSafeImportUrl(rawUrl); const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),10000); try { const response=await fetch(url,{signal:controller.signal,redirect:'manual',headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'MapRunImporter/1.0'}}); if(response.status>=300&&response.status<400) throw new Error('Redirecionamento bloqueado. Use a URL final da página.'); if(!response.ok) throw new Error(`Página indisponível (HTTP ${response.status}).`); const type=response.headers.get('content-type')||''; if(!type.includes('text/html')&&!type.includes('application/xhtml+xml')) throw new Error('A URL não retornou uma página HTML.'); const length=Number(response.headers.get('content-length')||0); if(length>2_000_000) throw new Error('A página excede o limite de importação.'); const html=await response.text(); if(html.length>2_000_000) throw new Error('A página excede o limite de importação.'); return extractEventMetadata(html,url); } catch(e) { if(e instanceof Error&&e.name==='AbortError') throw new Error('Tempo limite excedido ao acessar a página.'); throw e; } finally { clearTimeout(timer); } }
