'use client';
import { useEffect, useState } from 'react';
const MAX_SELECTED = 10;
export const DISCOVERY_V2_DISCOVER_REQUEST = { action: 'list-sources', sourceLimit: 3 } as const;
type AuditCandidate = { candidateId: string; sourceName: string; url: string; titleHint: string | null; classification: string };
type DiscoveryResponse = { report?: Record<string, unknown>; error?: string };
function isIndividualUrl(c: AuditCandidate) { try { const p=new URL(c.url).pathname; if(c.sourceName.startsWith('Bora Correr')) return /\/corrida\//.test(p); if(c.sourceName.startsWith('Corrida1')) return /^\/corridas\/[^/]+\/[^/]+\/\d{4}\//.test(p); if(c.sourceName==='Portal das Corridas') return /\/event-details\/[^/]+/.test(p); if(c.sourceName.startsWith('VamuCorrer')) return /\/corrida\/[^/]+/.test(p); return true; } catch { return false; } }
function isFuture(c: AuditCandidate) { const m=`${c.titleHint||''} ${c.url}`.match(/20\d{2}[-/]\d{2}[-/]\d{2}/); return !m || new Date(m[0].replaceAll('/','-')).getTime() >= Date.now(); }
async function fetchAudit() { const pages=await Promise.all([0,200,400,600,800].map(offset=>fetch(`/api/admin/discovery/candidates-audit?limit=200&offset=${offset}`).then(r=>r.json() as Promise<{candidates?:AuditCandidate[]}>))); return pages.flatMap(p=>p.candidates||[]); }
export function DiscoveryV2TestPanel() {
 const [state,setState]=useState<'idle'|'loading'|'success'|'error'>('idle'); const [result,setResult]=useState<DiscoveryResponse|null>(null); const [candidates,setCandidates]=useState<AuditCandidate[]>([]); const [selected,setSelected]=useState<string[]>([]); const [candidateId,setCandidateId]=useState(''); const [searchError,setSearchError]=useState('');
 useEffect(()=>{fetchAudit().then(rows=>{const eligible=rows.filter(c=>c.classification==='probable_event'&&isIndividualUrl(c)&&isFuture(c)); const quota=[['Bora Correr SP',3],['Corrida1 MG',2],['Portal das Corridas',2],['VamuCorrer MG',2],['Bora Correr RJ',1]] as const; const chosen=quota.flatMap(([name,count])=>eligible.filter(c=>c.sourceName===name&&!/aterradinho/i.test(c.titleHint||c.url)).slice(0,count)); setCandidates(chosen); setSelected(chosen.map(c=>c.candidateId));}).catch(()=>setCandidates([]));},[]);
 const addById=async()=>{setSearchError(''); const id=candidateId.trim(); if(!id)return; if(selected.includes(id)){setSearchError('Candidato duplicado.');return;} if(selected.length>=MAX_SELECTED){setSearchError('O máximo é 10 candidatos.');return;} try { const found=(await fetchAudit()).find(c=>c.candidateId===id); if(!found){setSearchError('Candidato inexistente.');return;} if(found.classification!=='probable_event'||!isIndividualUrl(found)||!isFuture(found)){setSearchError('Candidato precisa ser probable_event, página individual e futuro.');return;} setCandidates(v=>v.some(c=>c.candidateId===id)?v:[...v,found]); setSelected(v=>[...v,id]); setCandidateId(''); } catch { setSearchError('Não foi possível consultar o candidato.'); }};
 const runSelected=async()=>{setState('loading');setResult(null);try{const chunks=Array.from({length:Math.ceil(selected.length/2)},(_,i)=>selected.slice(i*2,i*2+2));const reports=[];for(const candidateIds of chunks){const response=await fetch('/api/admin/discovery/dry-run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'dry-run-selected',candidateIds,enableResearch:true,researchLimit:candidateIds.length,concurrency:1})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha no chunk seletivo.');reports.push(data.report);setResult({report:{progress: String(reports.reduce((sum, report) => sum + Number(report?.candidatesEvaluated || 0), 0)) + '/' + selected.length, chunks: reports}});}setState('success')}catch(error){setResult({error:error instanceof Error?error.message:'Falha no chunk seletivo.'});setState('error')}};
 return <section className="admin-note" aria-labelledby="discovery-v2-test-title"><strong id="discovery-v2-test-title">Discovery V2 — Teste</strong><p>Execução manual controlada para avaliar URLs candidatas.</p><hr/><strong>Dry-run seletivo</strong><p>{selected.length}/{MAX_SELECTED} candidatos selecionados.</p><input aria-label="Candidate ID" value={candidateId} onChange={e=>setCandidateId(e.target.value)} placeholder="candidateId" disabled={state==='loading'||selected.length>=MAX_SELECTED}/><button className="button" type="button" onClick={addById} disabled={state==='loading'||selected.length>=MAX_SELECTED}>Adicionar candidato</button>{searchError&&<p role="alert">{searchError}</p>}<ul>{candidates.filter(c=>selected.includes(c.candidateId)).map(c=><li key={c.candidateId}><strong>{c.titleHint||'Sem título'}</strong> · {c.sourceName}<br/><small>{c.candidateId} · {c.url}</small> <button className="button" type="button" onClick={()=>setSelected(v=>v.filter(id=>id!==c.candidateId))} disabled={state==='loading'}>Remover</button></li>)}</ul><button className="button" type="button" onClick={runSelected} disabled={state==='loading'||selected.length!==MAX_SELECTED}>Executar dry-run nos selecionados</button>{state==='error'&&<p role="alert">{result?.error||'Falha na operação.'}</p>}{state==='success'&&result?.report&&<pre role="status" style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(result.report,null,2)}</pre>}</section>;
}




