'use client';
import { useEffect, useState } from 'react';
export const DISCOVERY_V2_DISCOVER_REQUEST = { action: 'list-sources', sourceLimit: 3 } as const;
const RESEARCH_DIAGNOSTIC_CANDIDATE_ID = '9b8ee578-4e69-4aa6-9c80-e2d1446be783';
type SourceResult = { sourceId: string; sourceName: string; urlsFound: number; candidatesNew: number; candidatesExisting: number; candidatesPersisted: number; durationMs: number; success: boolean; error?: string; truncated?: boolean; discoveryLimit?: number };
type AuditCandidate = { candidateId: string; sourceName: string; url: string; titleHint: string | null; classification: string };
function isIndividualUrl(candidate: AuditCandidate) {
 try {
  const path = new URL(candidate.url).pathname;
  if (candidate.sourceName.startsWith('Bora Correr')) return /\/corrida\//.test(path);
  if (candidate.sourceName.startsWith('Corrida1')) return /^\/corridas\/[^/]+\/[^/]+\/\d{4}\//.test(path);
  if (candidate.sourceName === 'Portal das Corridas') return /\/event-details\/[^/]+/.test(path);
  if (candidate.sourceName.startsWith('VamuCorrer')) return /\/corrida\/[^/]+/.test(path) && !/\/corridas\//.test(path);
  return true;
 } catch { return false; }
}
type DiscoveryResponse = { discovery?: { sourcesProcessed: number; sourcesSucceeded: number; sourcesFailed: number; urlsFound: number; candidatesNew: number; candidatesExisting: number; candidatesPersisted: number; durationMs: number; errors: { source: string; error: string }[]; sourceResults: SourceResult[] }; report?: Record<string, unknown>; candidates?: { url: string; source: string; titleHint: string | null; discoveryMethod: string }[]; error?: string };
export function DiscoveryV2TestPanel() {
 const [state,setState]=useState<'idle'|'loading'|'success'|'error'>('idle'); const [result,setResult]=useState<DiscoveryResponse|null>(null); const [candidates,setCandidates]=useState<AuditCandidate[]>([]); const [selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{Promise.all([0,200,400,600].map(offset=>fetch(`/api/admin/discovery/candidates-audit?limit=200&offset=${offset}`).then(r=>r.json() as Promise<{candidates?:AuditCandidate[]}>))).then(pages=>{const rows=pages.flatMap(data=>data.candidates||[]).filter(c=>c.classification==='probable_event' && isIndividualUrl(c)); const quota=[['Bora Correr SP',3],['Corrida1 MG',2],['Portal das Corridas',2],['VamuCorrer MG',2],['Bora Correr RJ',1]] as const; const chosen=quota.flatMap(([name,count])=>rows.filter(c=>c.sourceName===name).slice(0,count)); const ids=chosen.map(c=>c.candidateId); setCandidates(chosen); setSelected(ids);}).catch(()=>setCandidates([]));},[]);
 async function run(){setState('loading');setResult(null);try{const headers={'Content-Type':'application/json'};const lr=await fetch('/api/admin/discovery/dry-run',{method:'POST',headers,body:JSON.stringify(DISCOVERY_V2_DISCOVER_REQUEST)});const listed=await lr.json() as {sources?:{id:string;name:string}[];error?:string};if(!lr.ok||!listed.sources)throw new Error(listed.error||'Não foi possível carregar as fontes.');const sourceResults:SourceResult[]=[];const started=Date.now();for(const source of listed.sources.slice(0,3)){const response=await fetch('/api/admin/discovery/dry-run',{method:'POST',headers,body:JSON.stringify({action:'discover-source',sourceId:source.id})});const data=await response.json() as Record<string,unknown>;const item:SourceResult={sourceId:source.id,sourceName:source.name,urlsFound:Number(data.urlsFound||0),candidatesNew:Number(data.candidatesNew||0),candidatesExisting:Number(data.candidatesExisting||0),candidatesPersisted:Number(data.candidatesPersisted||0),durationMs:Number(data.durationMs||0),success:data.success===true,error:typeof data.error==='string'?data.error:undefined,truncated:data.truncated===true,discoveryLimit:Number(data.discoveryLimit||200)};sourceResults.push(item)}const totals=sourceResults.reduce((a,i)=>({urlsFound:a.urlsFound+i.urlsFound,candidatesNew:a.candidatesNew+i.candidatesNew,candidatesExisting:a.candidatesExisting+i.candidatesExisting,candidatesPersisted:a.candidatesPersisted+i.candidatesPersisted}),{urlsFound:0,candidatesNew:0,candidatesExisting:0,candidatesPersisted:0});setResult({discovery:{sourcesProcessed:sourceResults.length,sourcesSucceeded:sourceResults.filter(i=>i.success).length,sourcesFailed:sourceResults.filter(i=>!i.success).length,...totals,durationMs:Date.now()-started,errors:sourceResults.filter(i=>!i.success).map(i=>({source:i.sourceName,error:i.error||'Falha controlada.'})),sourceResults}});setState('success')}catch(error){setResult({error:error instanceof Error?error.message:'Não foi possível executar a descoberta.'});setState('error')}}
 async function runSelected(){setState('loading');setResult(null);try{const response=await fetch('/api/admin/discovery/dry-run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'dry-run-selected',candidateIds:selected,enableResearch:true,researchLimit:10,concurrency:2})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha no dry-run seletivo.');setResult(data);setState('success')}catch(error){setResult({error:error instanceof Error?error.message:'Falha no dry-run seletivo.'});setState('error')}}
 async function runDiagnostic(){const candidateId=RESEARCH_DIAGNOSTIC_CANDIDATE_ID;setState('loading');setResult(null);try{const response=await fetch('/api/admin/discovery/dry-run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'research-diagnostic',candidateIds:[candidateId]})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha no diagnóstico.');setResult({report:data});setState('success')}catch(error){setResult({error:error instanceof Error?error.message:'Falha no diagnóstico.'});setState('error')}}
 const summary=result?.discovery; return <section className="admin-note" aria-labelledby="discovery-v2-test-title"><strong id="discovery-v2-test-title">Discovery V2 — Teste</strong><p>Execução manual controlada para avaliar URLs candidatas.</p><button className="button" type="button" onClick={run} disabled={state==='loading'}>{state==='loading'?'Carregando…':'Executar discovery em 3 fontes'}</button><hr/><strong>Dry-run seletivo</strong><p>{candidates.length} candidatos determinísticos selecionados.</p><ul>{candidates.map(c=><li key={c.candidateId}><label><input type="checkbox" checked={selected.includes(c.candidateId)} disabled={state==='loading'} onChange={e=>setSelected(v=>e.target.checked?[...v,c.candidateId]:v.filter(id=>id!==c.candidateId))}/> {c.titleHint||c.url} · {c.sourceName}</label></li>)}</ul><button className="button" type="button" onClick={runSelected} disabled={state==='loading'||selected.length===0}>Executar dry-run nos selecionados</button>{<button className="button" type="button" onClick={runDiagnostic} disabled={state==='loading'}>Diagnosticar research do Aterradinho</button>}{state==='error'&&<p role="alert">{result?.error||'Falha na operação.'}</p>}{state==='success'&&result?.report&&<pre role="status" style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(result.report,null,2)}</pre>}{state==='success'&&summary&&<div role="status"><p>{summary.sourcesSucceeded}/{summary.sourcesProcessed} fontes · {summary.urlsFound} URLs · {summary.candidatesNew} novas · {summary.candidatesExisting} existentes · {summary.candidatesPersisted} persistidas · {summary.durationMs} ms</p>{summary.errors.length>0&&<ul>{summary.errors.map(e=><li key={e.source}>{e.source}: {e.error}</li>)}</ul>}<ul>{summary.sourceResults.map(s=><li key={s.sourceId}>{s.sourceName}: {s.success?`${s.urlsFound} URLs, ${s.candidatesNew} novas, ${s.candidatesExisting} existentes${s.truncated?' (limite atingido)':''}`:`erro: ${s.error}`}</li>)}</ul></div>}</section>
}
