'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Search, ExternalLink, Ban, RefreshCw } from 'lucide-react';
import { formatDate } from '@/features/events/discovery';

export function DiscoveryQueue({ initial }: { initial: Record<string, unknown>[] }) {
  const [rows, setRows] = useState(initial), [status, setStatus] = useState('pending'), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [reenriching, setReenriching] = useState<string | null>(null);
  const visible = rows.filter((row) => status === 'all' || row.status === status);
  async function run() { setBusy(true); const response = await fetch('/api/admin/discovery/run', { method: 'POST' }); const data = await response.json(); setBusy(false); setMessage(response.ok ? `${data.summary.discovered} encontradas · ${data.summary.newCandidates} novas · ${data.summary.duplicates} duplicadas · ${data.summary.errors} erros` : data.error || 'Falha na busca.'); }
  async function update(id: string) { await fetch(`/api/admin/discovery/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'ignored' }) }); setRows(rows.map((row) => row.id === id ? { ...row, status: 'ignored' } : row)); }
  async function reenrich(id: string) { setReenriching(id); const response = await fetch(`/api/admin/discovery/${id}/reenrich`, { method: 'POST' }); const data = await response.json(); setReenriching(null); if (!response.ok) { setMessage(data.error || 'Não foi possível re-enriquecer.'); return; } setRows(rows.map((row) => row.id === id ? { ...row, ...data.candidate } : row)); setMessage('Candidato re-enriquecido.'); }
  return <><div className="admin-heading"><div><span className="eyebrow green">DESCOBERTA CONTROLADA</span><h1>Fila de descobertas</h1></div><button className="button" disabled={busy} onClick={run}><RefreshCw size={17}/>{busy ? 'Buscando…' : 'Buscar novas corridas'}</button></div>{message && <p className="import-notice" role="status">{message}</p>}<select aria-label="Status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="pending">Pendentes</option><option value="imported">Importados</option><option value="ignored">Ignorados</option><option value="duplicate">Duplicados</option><option value="all">Todos</option></select><div className="table-scroll"><table className="admin-table"><thead><tr><th>Possível corrida</th><th>Fonte</th><th>Status</th><th>Ações</th></tr></thead><tbody>{visible.map((row) => <tr key={String(row.id)}><td><strong>{String(row.name)}</strong><p>{String(row.city || 'Cidade não encontrada')}{row.state ? ` / ${String(row.state)}` : ''}{row.event_date ? ` · ${formatDate(String(row.event_date))}` : ''}</p></td><td>{String((row.discovery_sources as { name?: string })?.name || 'Fonte')}</td><td>{String(row.quality_status || 'incomplete')} · {String(row.status)}{Boolean(row.duplicate_event_id) && <small> possível duplicata</small>}</td><td className="queue-actions"><Link href={`/admin/eventos/importar?candidate=${encodeURIComponent(String(row.id))}`} title="Revisar e importar"><Search size={17}/></Link><a href={String(row.source_url)} target="_blank" rel="noopener noreferrer" title="Abrir fonte"><ExternalLink size={17}/></a>{row.status === 'pending' && <button onClick={() => update(String(row.id))} title="Ignorar"><Ban size={17}/></button>}{row.status === 'pending' && ['incomplete', 'conflict'].includes(String(row.quality_status || 'incomplete')) && <button onClick={() => reenrich(String(row.id))} disabled={reenriching === String(row.id)} title="Re-enriquecer manualmente">{reenriching === String(row.id) ? '…' : '↻'}</button>}</td></tr>)}</tbody></table></div></>;
}

