import type { SupabaseClient } from '@supabase/supabase-js';
import { normalizeBrazilianState } from '@/features/locations/state';
export type GeocodingPrecision = 'address' | 'venue' | 'city';
export interface GeocodeEventLocationInput { address?: string|null; venue?: string|null; city?: string|null; state?: string|null; country?: string|null; }
export interface GeocodeResult { latitude: number; longitude: number; precision: GeocodingPrecision; provider: 'nominatim'; }
type FetchLike = typeof fetch;
const clean = (value?: string|null) => (value || '').replace(/[\[\]{}]/g, '').trim();
const validNumber = (value: unknown) => typeof value === 'number' && Number.isFinite(value) && value !== 0;
function stateMatches(result: Record<string, unknown>, state: string) { const address = result.address; if (!address || typeof address !== 'object') return true; const data = address as Record<string, unknown>; const code = String(data.state_code || '').toLowerCase().replace('br-', ''); const name = String(data.state || ''); return !state || code === state.toLowerCase() || normalizeBrazilianState(name) === state; }
async function search(query: string, state: string, precision: GeocodingPrecision, fetchImpl: FetchLike): Promise<GeocodeResult|null> { try { const response = await fetchImpl(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=3&countrycodes=br&q=${encodeURIComponent(query)}`, { headers: { 'User-Agent': 'MapRun/1.0 (geocoding)' }, signal: AbortSignal.timeout(8000) }); if (!response.ok) return null; const body: unknown = await response.json(); if (!Array.isArray(body)) return null; for (const item of body) { if (!item || typeof item !== 'object') continue; const result = item as Record<string, unknown>; const latitude = Number(result.lat), longitude = Number(result.lon); const address = result.address as Record<string, unknown>|undefined; const country = String(address?.country_code || '').toLowerCase(); if (!validNumber(latitude) || !validNumber(longitude) || country && country !== 'br' || !stateMatches(result, state)) continue; return { latitude, longitude, precision, provider: 'nominatim' }; } } catch { /* best effort */ } return null; }
export async function geocodeEventLocation(input: GeocodeEventLocationInput, options: { client?: SupabaseClient; fetchImpl?: FetchLike } = {}): Promise<GeocodeResult|null> { const address = clean(input.address), venue = clean(input.venue), city = clean(input.city), state = normalizeBrazilianState(input.state), country = clean(input.country) || 'Brasil'; if (!city || !state) return null; const fetchImpl = options.fetchImpl || fetch; if (options.client) { try { const { data } = await options.client.from('geocoded_locations').select('latitude,longitude,provider').eq('city', city).eq('state', state).eq('country', 'BR').maybeSingle(); if (data && validNumber(Number(data.latitude)) && validNumber(Number(data.longitude))) return { latitude: Number(data.latitude), longitude: Number(data.longitude), precision: 'city', provider: 'nominatim' }; } catch { /* optional cache */ } } const attempts: Array<[string, GeocodingPrecision]> = []; if (address) attempts.push([[address, venue, city, state, country].filter(Boolean).join(', '), 'address']); if (venue) attempts.push([[venue, city, state, country].filter(Boolean).join(', '), 'venue']); attempts.push([[city, state, country].filter(Boolean).join(', '), 'city']); for (const [query, precision] of attempts) { const result = await search(query, state, precision, fetchImpl); if (!result) continue; if (precision === 'city' && options.client) { try { await options.client.from('geocoded_locations').upsert({ city, state, country: 'BR', latitude: result.latitude, longitude: result.longitude, provider: result.provider, updated_at: new Date().toISOString() }, { onConflict: 'city,state,country' }); } catch { /* optional cache */ } } return result; } return null; }
